# Ruby/Rails Dev Environment (gewo/ruby)
FROM gewo/ruby-dependencies
MAINTAINER Gebhard Wöstemeyer <g@ctr.lc>

ENV APP_RUBY_VERSION 2.3.1
RUN rvm install ruby-${APP_RUBY_VERSION} --default
CMD ["/bin/bash"]
