#!/bin/bash
set -e
set -x

if [ ! -e /data/ibdata1 ]; then
  mysql_install_db
  mysqld_safe &
  sleep 10
  mysql -e "GRANT ALL ON *.* to 'root'@'%'; FLUSH PRIVILEGES"
  killall mysqld
  sleep 10
fi

mysqld_safe
